CREATE DATABASE db;

USE db;

CREATE TABLE ARTICLE (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(80) NOT NULL,
    MARCA VARCHAR(80) NOT NULL,
    ESTADO BOOLEAN NOT NULL DEFAULT TRUE,
    FECHA_MODIFICACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);