version: "3.8"

services:
  app:
    build: .
    container_name: my_node_app
    ports:
      - "8090:8090"
    environment:
      DB_HOST: my_sql
      MYSQL_USER: root
      MYSQL_PASSWORD: "12345"
      MYSQL_DATABASE: db
      DB_PORT: "3306"
    env_file:
      - .env
    volumes:
      - ./:/myapp
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345"
      MYSQL_DATABASE: db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data: 
  node_modules_cache:
