version: "3.8"

services:
  app:
    build: .
    container_name: my_node_app
    ports:
      - "8090:8090"
    environment:
      DB_HOST: ${DB_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      DB_PORT: "${MYSQL_PORT}"
    env_file:
      - .env
    volumes:
      - ./:/myapp
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:8.0
    container_name: my_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data: # Volumen para los datos de MySQL
  node_modules_cache: # Volumen para node_modules
