services:
  app:
    build: .
    container_name: my_node_app
    ports:
      - "8090:8090"
    env_file:
      - .env.production
    volumes:
      - ./src:/myapp/src
      - ./package.json:/myapp/package.json
      - node_modules_cache:/myapp/node_modules

    networks:
      - mynetwork
    depends_on:
      - mysql-prod

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    networks:
      - mynetwork

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: nodeexporter
    ports:
      - "9100:9100"
    networks:
      - mynetwork

  mysql-dev:
    image: mysql:8.0
    container_name: mysql-dev-container
    env_file:
      - .env.development
    ports:
      - "3307:3306"
    volumes:
      - mysql-dev-data:/var/lib/mysql
    networks:
      - mynetwork

  mysql-prod:
    image: mysql:8.0
    container_name: mysql-prod-container
    env_file:
      - .env.production
    ports:
      - "3308:3306"
    volumes:
      - mysql-prod-data:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  node_modules_cache: {}
  mysql-dev-data: {}
  mysql-prod-data: {}
