services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db_test
    environment:
      MYSQL_ROOT_PASSWORD: "12345"  
      MYSQL_DATABASE: db           
    ports:
      - "3309:3306"  
    volumes:
      - mysql_data_test:/var/lib/mysql  

volumes:
  mysql_data_test:
