scrape_configs:
  # Configuración para tu aplicación Node.js
  - job_name: 'my_node_app'
    metrics_path: '/monitor/metrics'
    scrape_interval: 15s
    static_configs:
      - targets: ['app:8090']

  # Configuración para Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['nodeexporter:9100']
